name: Build
on:
  push:
    branches: [master, main]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up
        run: |
          docker stop web-nginx-1
          docker stop web-frontend-1
          docker stop web-backend-1

      - name: Build and up
        run: docker compose up --build
