name: Build
on:
  push:
    branches: [master, main]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: docker compose up --build
